name: AIBotChat
version: 2.0
main: de.zfzfg.aichat.AIBotPlugin
api-version: 1.20
author: Sterra.Online
website: https://sterra.online
description: AI-powered chat assistant using text-generation-webui

commands:
  ai:
    description: Ask the AI a question
    usage: /ai <your question>
    aliases: [ask, bot, ki]
    permission: aibotchat.use  # Optional, depending on config

  aireload:
    description: Reload the AIBotChat configuration
    usage: /aireload
    permission: aibotchat.admin

permissions:
  aibotchat.use:
    description: Allows using the /ai command
    default: true  # Everyone has it by default, but config can override

  aibotchat.admin:
    description: Allows reloading the config
    default: op